### ISSUE TITLE
Examples incorporating alcotest-lwt

### ISSUE THREAD

**Issue by kennetpostigo** [mirage/alcotest#118]
I'm not exactly sure how to use this package to test `lwt`, I tried to look at two other repos that depend on `alcotest-lwt` but I couldn't quite figure out how it should be used. Is there any chance there could be some simple examples on how best to incorporate `alcotest-lwt` into our tests?

**Comment by talex5** [comment]
Hmm, yes, more documentation here would be good.

The basic idea is that instead of providing a test function in the form `unit -> unit`, you provide one with the type `unit -> unit Lwt.t` and alcotest-lwt calls `Lwt_main.run` for you.

However, there are a couple of extra features:

- If an async exception occurs, it will cancel your test case for you and fail it (rather than exiting the process).
- You get given a switch, which will be turned off when the test case finishes (or fails). You can use that to free up any resources.

**Comment by bruce-ricard** [comment]
The type of `test-case` is `bytes ->                                                                                                                                                                                                    Alcotest.speed_level ->                                                                                                                                                                                     (Lwt_switch.t -> 'a -> unit Lwt.t) -> 'a Alcotest.test_case`. Is the `'a` practically always `unit` since `Alcotest.run` takes a `unit Alcotest.test list` as argument?

I tried to use the framework, and I just ignore completely the `Lwt_switch` argument since I don't really understand at the moment what I am supposed to do with it, and my tests run very well. Could you please provide an example of why/how to use the switch?

**Comment by samoht** [comment]
The `'a` argument is what is passed to the test cases and you need to pass an extra arguments to the tests. Most of the time, it is indeed `()` and you have nothing to worry about.

However, if you want to use that parameter, you can do something like that:

```
let test_int i = Alcotest.(check int) "This is a nice integer" i 42

let int =
  let doc = "What is your prefered number?" in
  Cmdliner.Arg.(required & opt (some int) None & info ["n"] ~doc ~docv:"NUM")

let () =
  Alcotest.run_with_args "foo" int [
    "all", ["int", `Quick, test_int]
  ]
```

And:

```
$ _build/default/foo.exe test
foo.exe: required option -n is missing
$ _build/default/foo.exe test -n 42
Testing foo.
[OK]                all          0   int.
The full test results are available in `_build/_tests`.
Test Successful in 0.000s. 1 test run.
```

(note you must use a optional argument here, not a positional one otherwise alcotest will be confused). 

The switch is useful for `lwt` tests which need to manage resources, for instance when there is a global failure and you want to free up everything:

```
let free () = print_endline "freeing all resources"; Lwt.return ()

let test_lwt switch () =
  Lwt_switch.add_hook (Some switch) free;
  Lwt.async (fun () -> failwith "All is broken");
  Lwt_unix.sleep 10.

let () =
  Alcotest.run "foo" [
    "all", [
      Alcotest_lwt.test_case "one" `Quick test_lwt
    ]
  ]
```

will display:

```
$ _build/default/foo.exe
Testing foo.
[ERROR]             all          0   one.
-- all.000 [one.] Failed --
in _build/_tests/all.000.output:
freeing all resources
[failure] All is broken
```

**Comment by bruce-ricard** [comment]
Thank you @samoht that was very helpful. 
Three other things from somebody with abour 3h of experience with alcotest:

1. I have not been enable to find what `Quick` and `Slow` are. I'm guessing I'll get a warning if a `Quick` test takes too long to run?
2. I am always getting `Test Successful in 0.000s. 5 tests run.`. I have tried using `Unix.sleep` and `Lwt_unix.sleep` I cannot increase this `0.000s`. I strongly doubt that my tests are taking less than 1ms to run. Is that a bug or am I doing something wrong?
3. `The full test results are available in '_build/_tests'.` This is technically incorrect. The `_build` directory seems to be placed where the tests are, which for me is inside of a `lib/` directory.

Apart from that I did really enjoy starting to learn your test framework, it is very nice. But yes as the 2 first posts of this thread mention, the documentation could be improved to help new users.
