### ISSUE TITLE
Alcotest output requires verbose flag

### ISSUE THREAD

**Issue by basus** [mirage/alcotest#121]
I'm trying to use Alcotest to test some code with the following types and test function. However, unless I use the `"--verbose"` flag in `argv` when calling the Alcotest `run` function, I get no output, even if there are lots of test failures. Using the `"--verbose"` flag everything displays fine.

```ocaml
type test = { citation : string option
            ; caption  :  string option
            ; expected : Sexp.t option
            ; program  :  string} [@@deriving sexp]

type suite = { title : string
             ; reference : string option
             ; tests : test list } [@@deriving sexp]


(** Apply functions to the test programs in a suite *)
let test (s:suite) ~f =
  let open Alcotest in
  let sexp = testable Sexp.pp Sexp.equal in
  let test_set = List.mapi s.tests ~f:(fun i test ->
      let name = match test.caption with Some s -> s | None -> Int.to_string i in
      let exp = match test.expected with Some s -> s | None -> Sexp.Atom "" in
      let fn = fun () -> (check sexp) name exp (f test.program) in
      (name, `Quick, fn)
    ) in
  let argv = Array.of_list ["--verbose"] in
  run s.title ~argv [("Suite", test_set)]
```

I wonder if it's related to how I'm calling `test`, using `Command` from a separate `main.ml` file, where `Model` is the module containing the bulk of the project code:

```ocaml
let test =
  Command.basic_spec
    ~summary:"Run the test cases from the given file"
    Command.Spec.(
      empty
      +> anon ("filename" %: file)
      ++ common )
    ( fun filename debug verbose () ->
        let open Test in
        let suite = from_filename filename in
        let runner = (fun s -> Model.of_string s |> Model.to_sexp ) in
        test ~f:runner suite )
```

**Comment by CraigFe** [comment]
This is certainly odd. As discussed in #163, the first element of `~argv` is not interpreted as an option by `Alcotest.run` (since `argv[0]` is the name by which the program was called). As far as I can tell, it has always been this way, so I can't imagine how passing `~argv:[| "--verbose" |]` would ever have changed the behaviour. As such, I'll close this for now. If you still have a working example of this failing, let me know and I'll re-open the issue.

As it happens, in the next Alcotest release, we will have dedicated options to `Alcotest.run` for all of the flags that can be set at the command line (e.g. `?verbose:bool`), which should limit confusions surrounding the use of this option.
