### ISSUE TITLE
tests location hint is wrong with dune

### ISSUE THREAD

**Issue by samoht** [mirage/alcotest#135]
See https://github.com/samoht/dune-release/pull/69#issuecomment-419905777

**Comment by m-harrison** [comment]
The problem here is that `dune` appears to alter the current working directory as part of `dune build @runtest`. When `default_cmd` calls into `run_registred_tests` the `Cmdliner` parameter of `test_dir` gets evaluated. `dune` doesn't provide a `-o` parameter and so the default value is used. This default value is a relative path and so this relative path is going to be traversed from the current working directory set by `dune`.

The result of this is that as observed, the test logs get dropped in `/Users/matt/git/{project name}/_build/default/lib_tests/_build/_tests`, but when reporting the test location back out to the user the current code reports the literal `t.test_dir` which is the relative path - hence the confusing user experience.

The fix I'm proposing (and that I'll add to my existing PR) is to rather than default `test_dir` to the relative path `"_build/_tests"`, make sure that it gets set to the absolute path prefixed by the current working directory.
