### ISSUE TITLE
Silently ignoring duplicate test names

### ISSUE THREAD

**Issue by CraigFe** [mirage/alcotest#175]
If Alcotest is run on a suite with duplicate `(test_name, index)` cases, the log output of the last instance will overwrite those of the former. Consider the following example:

```
  Alcotest.run "Utils"
    [ ( "duplicated_name",
        [ Alcotest.test_case "Lower case" `Quick test_lowercase;
          Alcotest.test_case "Capitalization" `Quick test_capitalize
        ] );
      ( "duplicated_name",
        [ Alcotest.test_case "String mashing" `Quick test_str_concat ] )
    ]
```

This produces only two logs: `duplicated_name.000.output` and `duplicated_name.001.output`.

**Comment by aantron** [comment]
I think that duplicate test suite names, and duplicate test names within a suite, should be forbidden. They present a usability problem when reading test failure output, because the developer may waste time going to the wrong test.

I think under typical circumstances, a developer has access to all the tests that are linked into the tester, so it's not a problem to fix a duplicate name error.

This would also make filtering more intuitive, as we wouldn't have to refer to tests by number. The number can also change due to reordering.

Is there a reason this wasn't done originally? I couldn't easily find something in the blame, comments, or the README.

**Comment by CraigFe** [comment]
I agree that duplicate suite names should be forbidden (although we probably _also_ shouldn't be using test names directly for FS interactions, since it limits the charset usable in test names -- #171). My candidate solution in #176 requires that test names be lowercase unique.

I don't know why it wasn't being done originally, but I had to do a little refactoring to make it possible to check for uniqueness, so perhaps that's why :slightly_smiling_face: Until we fix the problem of adding proper unit tests to Alcotest, these kinds of problems are going to crop up occasionally
