### ISSUE TITLE
Show only output tail (last N lines) when reporting error

### ISSUE THREAD

**Issue by mjambon** [mirage/alcotest#199]
I have some tests that produce thousands of lines of logs. When a test fails, what I'd like is to see only the last 10 or 20 lines. Currently the whole output is printed, which is way too long and prevents me from seeing the report printed by alcotest before that.

So, I would like to add an option for truncating the logs printed to the console to some number of lines. Here's some sample output:
```
$ ./floats.exe
Testing Float tests.
This run has ID `49F10EBE-1DE5-42D4-9478-2AEBBBF1D935`.
[FAIL]              Edge cases            0   NaN.
[OK]                Edge cases            1   ∞.
[OK]                Other floats          0   others.
-- Edge cases.000 [NaN.] Failed --
in `/home/martin/tmp/alcotest/_build/default/examples/_build/_tests/49F10EBE-1DE5-42D4-9478-2AEBBBF1D935/edge cases.000.output`:
... (truncated)
x
x
x
x
x
x
x
x
x
x
x
x
x
x
x
[exception] File "examples/floats.ml", line 34, characters 2-8: Assertion failed

The full test results are available in `/home/martin/tmp/alcotest/_build/default/examples/_build/_tests/49F10EBE-1DE5-42D4-9478-2AEBBBF1D935`.
1 error! in 0.000s. 3 tests run.
```

We could make this truncation optional iff there's a worry that it break compatibility for some people. We could also add an option to specify how many lines are shown.

Does it look like a reasonable proposal?

**Comment by CraigFe** [comment]
Thanks for the proposal (and the patch in https://github.com/mirage/alcotest/pull/200); I'm in favour of supporting this feature.

Personally, I think the truncation should be optional and opt-in via a CLI option and an environment variable (since unfortunately environment variables are our only way to pass options via a `dune runtest` invocation). This would allow users to set their own idea of a 'reasonable' threshold that doesn't interfere with CI error logging or the experience of other collaborators on the same project.

**Comment by mjambon** [comment]
I agree with the truncation threshold being configurable. I'll modify #200 accordingly (most likely this weekend).
