### ISSUE TITLE
Unicode boxes do not track terminal width

### ISSUE THREAD

**Issue by emillon** [mirage/alcotest#277]
Hi,

On a terminal 85 columns wide, the default behavior outputs boxes that are not readable:

![alcotest](https://user-images.githubusercontent.com/496345/92930424-576cfa00-f442-11ea-834c-7428be7e0452.png)

That's related to #72 but I think that's not the whole story because it seems that alcotest now assumes that the terminal is 80 columns wide, which would fit.

Thanks!

**Comment by CraigFe** [comment]
Indeed, the more fundamental problem here is that we're not yet using `TIOCGWINSZ`. With a stub for that, we could fix both this and #72 very easily.

**Comment by emillon** [comment]
But I think there's something off in the calculation too, otherwise something that assumes a 80 column terminal would work fine on a 85 column terminal, wouldn't it?

**Comment by CraigFe** [comment]
Indeed. The formatting doesn't try very hard to meet an 80 column width at the moment (because this is already an arbitrary choice). In particular, long test names are printed as-is with no wrapping (as in [this test case](https://github.com/mirage/alcotest/blob/master/test/e2e/alcotest/failing/long_test_case_name.expected#L7-L9), which is similar to the example you've given), with the idea being that the user currently knows better than Alcotest how wide they want their output.

There's nothing particularly challenging about providing a guarantee of "no lines longer than terminal width", but IMO not much point in doing that until we're actually measuring terminal width.
