### ISSUE TITLE
Correct way to set up `Fmt` and `Logs` reporter/style?

### ISSUE THREAD

**Issue by MisterDA** [mirage/alcotest#334]
The OBuilder test executable has this code (it's using alcotest and alcotest-lwt):

```ocaml
let () =
  Logs.(set_level ~all:true (Some Debug));
  Logs.set_reporter @@ Logs.format_reporter ();
```

I wonder if that's the best way to set the reporter: the logs reported by the app aren't coloured, but alcotest is. If alcotest is already detecting whether it's running in a tty and allows the user to override the colour options and the verbosity, it seems that this should be forwarded to the test executable, and I should use e.g. `fmt.tty` or `logs.fmt` or `fmt.cli` there.
So, what's the best way to initialise  `Logs` and `Fmt` in the test executable and let alcotest manage most of it?

Thanks!

**Comment by CraigFe** [comment]
Use [`Logs_fmt.reporter`](https://github.com/dbuenzli/logs/blob/master/src/logs_fmt.ml#L36-L37) rather than `Logs.format_reporter` if you'd like the tags to be pretty-printed with `Fmt.styled`. Other than that, your snippet looks good to me.

(Alcotest handles the call to `Fmt_tty.setup_std_outputs`, so users who are using `Fmt` to conditionally add styles don't need to do that.)
