### ISSUE TITLE
how to run a single test?

### ISSUE THREAD

**Issue by mimoo** [mirage/alcotest#377]
I have a test defined as such that I'm trying to call:

```
let circuit_tests =
  [ ( "boolean circuit"
    , `Quick
    , check_json ~input_typ:BooleanCircuit.input_typ
        ~return_typ:BooleanCircuit.return_typ ~circuit:BooleanCircuit.main
        "simple.json" )
```

I've been trying to pass the name as such:

```
ALCOTEST_COLOR=always dune test --no-buffer . -- 'boolean circuit'
```

but I get the following error:

```
Error: Don't know about directory "src/lib/crypto/snarky_tests/boolean
circuit" specified on the command line!
```

**Comment by MisterDA** [comment]
You cannot forward supplementary arguments from `dune test -- args` to the test executable, because there could be plenty of tests executables, and Dune wouldn't know which one you're actually trying to use (`dune test` runs _all_ the tests executables).
What you can do instead is write the argument in the `dune` file using an [action stanza](https://dune.readthedocs.io/en/stable/concepts.html#user-actions), or use `dune exec` with your test executable.

```
dune exec -- src/lib/crypto/snarky_tests/test.exe 'boolean circuit'
```

btw, using Dune 3.7.0 and Alcotest 1.7.0, you shouldn't have to specify `ALCOTEST_COLOR`.

**Comment by mimoo** [comment]
oh I see, I wish I didn't have to write the full path and `.exe` but this is what we have to day I guess :D

**Comment by mimoo** [comment]
now getting a new error

```
dune exec -- src/lib/crypto/snarky_tests/test.exe 'updated'                      
Error: Program "src/lib/crypto/snarky_tests/test.exe" not found!
```

**Comment by mimoo** [comment]
I'm getting "Invalid request (no tests to run, filter skipped everything)!" if I try with the additional `test` command: `snarky_tests.exe test 'some string'`

**Comment by mimoo** [comment]
OK I think I understand how to use this. I have to run this command first:

```
dune exec -- src/lib/crypto/snarky_tests/test.exe list
```

and I can only use the `test` command to execute a group of test that matches a name (I can't seem to match a test inside a group of test)

**Comment by MisterDA** [comment]
> I can't seem to match a test inside a group of test

Indeed, that's not possible with the current interface.
