### ISSUE TITLE
accent change aligment

### ISSUE THREAD

**Issue by fdagnat** [mirage/alcotest#5]
If the name of test case contain n accents, the ok, error message is moved n character to the right losing its alignment with other lines.

    open Alcotest
    let names = ["test de add";"test de add après ààààremove";"test de add"]
    let tc name = name,  `Quick, fun () -> ()
    let t_world = "tests de toto", List.map tc names
    let _ = run "pipo" [t_world]

**Comment by samoht** [comment]
Need to use some magic runes from some unicode library to fix this. Advice welcome (should probably be easy to do @dbuenzli's library)

**Comment by dbuenzli** [comment]
Counting Unicode scalar values as @dsheets suggests is not going to be enough, you need to count [grapheme clusters](http://unicode.org/glossary/#grapheme_cluster) for making correct layouts. 

If you are using OCaml pretty printers use [this function](http://erratique.ch/software/uuseg/doc/Uuseg_string.html#VALpp_utf_8). If not you can get the number of grapheme clusters in a string by using [this function](http://erratique.ch/software/uuseg/doc/Uuseg_string.html#VALfold_utf_8) as follows:

```ocaml
let grapheme_cluster_count s = 
  Uuseg_string.fold_utf_8 `Grapheme_cluster (fun count _ -> count + 1) 0 s
```

**Comment by dbuenzli** [comment]
> you need to count grapheme clusters for making correct layouts.

Just for the record, in the context of terminal rendering this is not true. In fact the problem is not really solvable in general in terminals because of the discrepancies between their text rendering engine and the general inability to be able to interact with them to measure the visual width of a string.

The next release of uucp will include a heuristic function developed by @pqwy that you can fold over the scalar values of an unicode string to get a width *approximation*. See https://github.com/dbuenzli/uucp/pull/5 and the various attached commits for more details. I'd still advise against using this for alcotest, at least until `uucp` switches to module aliases.
